default: &default
  host: db
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test: &TEST
  <<: *default
  database: db/production.sqlite3
